import Head from 'next/head'
import Link from 'next/link';
import { useEffect } from "react";
import { useRouter } from "next/router";
import { Layout } from "components/layout"
const  PageNotFound = () =>{
    const router = useRouter()
    useEffect(() => {
       setTimeout(()=>{
         router.push("/")
       },5000)
    },[])
    return (
        <Layout>
        <Head>
        <title>Page Not Found</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

        <section className=" bg-white ">
            <div className="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8">
                <div className="max-w-md mx-auto text-center">
                    <h1 className="text-7xl xl:text-8xl text-gray-400 font-bold mb-3">404</h1>
                    <h4 className="text-3xl xl:text-4xl font-bold mb-5 text-gray-400">Page Not Found</h4>
                    <Link href="/" className="inline-flex items-center px-6 py-4 font-semibold text-white transition-all duration-200 bg-blue-600 rounded-md hover:bg-blue-700 focus:bg-blue-700">Go Back To Homepage</Link>
                </div>
            </div>
        </section>
        </Layout>
    )
}

export default PageNotFound;